-- AllerFit seed chunk 09: menu_allergens 3151-3188
begin;

insert into public.menu_allergens (menu_id, allergen_id, presence_type, note, source_id)
values
  ((select id from public.menus where slug = 'hosigi-035'), (select id from public.allergens where code = 'wheat'), 'contains', '밀, 대두, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-035'), (select id from public.allergens where code = 'soybean'), 'contains', '밀, 대두, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-035'), (select id from public.allergens where code = 'milk'), 'contains', '밀, 대두, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-036'), (select id from public.allergens where code = 'wheat'), 'contains', '밀, 대두, 토마토, 난류, 우유, 닭고기, 쇠고기, 조개류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-036'), (select id from public.allergens where code = 'soybean'), 'contains', '밀, 대두, 토마토, 난류, 우유, 닭고기, 쇠고기, 조개류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-036'), (select id from public.allergens where code = 'tomato'), 'contains', '밀, 대두, 토마토, 난류, 우유, 닭고기, 쇠고기, 조개류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-036'), (select id from public.allergens where code = 'egg'), 'contains', '밀, 대두, 토마토, 난류, 우유, 닭고기, 쇠고기, 조개류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-036'), (select id from public.allergens where code = 'milk'), 'contains', '밀, 대두, 토마토, 난류, 우유, 닭고기, 쇠고기, 조개류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-036'), (select id from public.allergens where code = 'chicken'), 'contains', '밀, 대두, 토마토, 난류, 우유, 닭고기, 쇠고기, 조개류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-036'), (select id from public.allergens where code = 'beef'), 'contains', '밀, 대두, 토마토, 난류, 우유, 닭고기, 쇠고기, 조개류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-036'), (select id from public.allergens where code = 'shellfish'), 'contains', '밀, 대두, 토마토, 난류, 우유, 닭고기, 쇠고기, 조개류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-037'), (select id from public.allergens where code = 'wheat'), 'contains', '밀, 대두, 땅콩, 토마토, 난류, 우유, 닭고기, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-037'), (select id from public.allergens where code = 'soybean'), 'contains', '밀, 대두, 땅콩, 토마토, 난류, 우유, 닭고기, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-037'), (select id from public.allergens where code = 'peanut'), 'contains', '밀, 대두, 땅콩, 토마토, 난류, 우유, 닭고기, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-037'), (select id from public.allergens where code = 'tomato'), 'contains', '밀, 대두, 땅콩, 토마토, 난류, 우유, 닭고기, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-037'), (select id from public.allergens where code = 'egg'), 'contains', '밀, 대두, 땅콩, 토마토, 난류, 우유, 닭고기, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-037'), (select id from public.allergens where code = 'milk'), 'contains', '밀, 대두, 땅콩, 토마토, 난류, 우유, 닭고기, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-037'), (select id from public.allergens where code = 'chicken'), 'contains', '밀, 대두, 땅콩, 토마토, 난류, 우유, 닭고기, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-037'), (select id from public.allergens where code = 'beef'), 'contains', '밀, 대두, 땅콩, 토마토, 난류, 우유, 닭고기, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-038'), (select id from public.allergens where code = 'soybean'), 'contains', '대두, 난류, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-038'), (select id from public.allergens where code = 'egg'), 'contains', '대두, 난류, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-038'), (select id from public.allergens where code = 'beef'), 'contains', '대두, 난류, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-039'), (select id from public.allergens where code = 'soybean'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-039'), (select id from public.allergens where code = 'tomato'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-039'), (select id from public.allergens where code = 'egg'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-039'), (select id from public.allergens where code = 'milk'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-039'), (select id from public.allergens where code = 'beef'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-040'), (select id from public.allergens where code = 'soybean'), 'contains', '대두, 나류, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-040'), (select id from public.allergens where code = 'beef'), 'contains', '대두, 나류, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-041'), (select id from public.allergens where code = 'tomato'), 'contains', '토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-042'), (select id from public.allergens where code = 'soybean'), 'contains', '대두, 토마토, 난류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-042'), (select id from public.allergens where code = 'tomato'), 'contains', '대두, 토마토, 난류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-042'), (select id from public.allergens where code = 'egg'), 'contains', '대두, 토마토, 난류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-043'), (select id from public.allergens where code = 'soybean'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-043'), (select id from public.allergens where code = 'tomato'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-043'), (select id from public.allergens where code = 'egg'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-043'), (select id from public.allergens where code = 'milk'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1)),
  ((select id from public.menus where slug = 'hosigi-043'), (select id from public.allergens where code = 'beef'), 'contains', '대두, 토마토, 난류, 우유, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'hosigi') and url = 'https://www.9922.co.kr/allergenic-component' order by created_at desc limit 1))
on conflict (menu_id, allergen_id, presence_type) do update
set note = excluded.note, source_id = excluded.source_id;

commit;
