-- Dasarang Chicken final allergy seed
-- Final menu list separates bone and boneless variants.
begin;

insert into public.brands (category_id, slug, name, official_url, allergen_source_url, data_status, last_checked_at, display_order, is_active)
values
  ((select id from public.categories where slug = 'chicken'), 'dasarang', '다사랑치킨', 'https://xn--2j1bs2g1tjbiouwc.com', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', 'official_verified', '2026-06-29', 3, true)
on conflict (slug) do update
set category_id = excluded.category_id, name = excluded.name, official_url = excluded.official_url, allergen_source_url = excluded.allergen_source_url, data_status = excluded.data_status, last_checked_at = excluded.last_checked_at, display_order = excluded.display_order, is_active = true;

insert into public.data_sources (brand_id, title, source_type, url, checked_at, note)
values
  ((select id from public.brands where slug = 'dasarang'), '다사랑치킨 공식 알레르기 정보', 'official_page', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', '최종 메뉴 기준 뼈/순살 분리; 공식 알레르기 표를 메뉴명에 매칭; 원산지 별도 확인 필요')
on conflict (brand_id, source_type, url) do update
set title = excluded.title, checked_at = excluded.checked_at, note = excluded.note;

update public.menus
set is_active = false
where brand_id = (select id from public.brands where slug = 'dasarang')
  and slug not in ('dasarang-bone-fried', 'dasarang-bone-yangnyeom', 'dasarang-bone-hwasal', 'dasarang-bone-blackbuster', 'dasarang-bone-redmagic', 'dasarang-bone-gangjeong', 'dasarang-boneless-fried', 'dasarang-boneless-yangnyeom', 'dasarang-boneless-hwasal', 'dasarang-boneless-blackbuster', 'dasarang-boneless-redmagic', 'dasarang-boneless-gangjeong', 'dasarang-boneless-chippurin', 'dasarang-boneless-pandora', 'dasarang-boneless-oriental-pa', 'dasarang-boneless-cream-onion', 'dasarang-boneless-tangsuyuk', 'dasarang-boneless-yuringi', 'dasarang-boneless-chili');

insert into public.menus (brand_id, category_id, slug, name, source_url, last_checked_at, menu_status, is_active)
values
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-bone-fried', '후라이드 치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-bone-yangnyeom', '양념치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-bone-hwasal', '화살치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-bone-blackbuster', '블랙버스터 치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-bone-redmagic', '레드매직 치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-bone-gangjeong', '닭강정', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-fried', '순살 후라이드치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-yangnyeom', '순살 양념치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-hwasal', '순살 화살치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-blackbuster', '순살 블랙버스터 치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-redmagic', '순살 레드매직 치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-gangjeong', '순살 닭강정', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-chippurin', '순살 치뿌린치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-pandora', '순살 판도라치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-oriental-pa', '순살 오리엔탈 파치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-cream-onion', '순살 크림양파치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-tangsuyuk', '순살 치킨탕수육', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-yuringi', '순살 치킨유린기', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true),
  ((select id from public.brands where slug = 'dasarang'), (select id from public.categories where slug = 'chicken'), 'dasarang-boneless-chili', '순살 칠리치킨', 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point', '2026-06-29', 'active', true)
on conflict (slug) do update
set brand_id = excluded.brand_id, category_id = excluded.category_id, name = excluded.name, source_url = excluded.source_url, last_checked_at = excluded.last_checked_at, menu_status = excluded.menu_status, is_active = true;

delete from public.menu_allergens
where menu_id in (select id from public.menus where brand_id = (select id from public.brands where slug = 'dasarang'));

insert into public.menu_allergens (menu_id, allergen_id, presence_type, note, source_id)
values
  ((select id from public.menus where slug = 'dasarang-bone-fried'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-fried'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-fried'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-fried'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-yangnyeom'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-yangnyeom'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-yangnyeom'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-yangnyeom'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-yangnyeom'), (select id from public.allergens where code = 'tomato'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-yangnyeom'), (select id from public.allergens where code = 'egg'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-hwasal'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-hwasal'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-hwasal'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-hwasal'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-hwasal'), (select id from public.allergens where code = 'shellfish'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-blackbuster'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-blackbuster'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-blackbuster'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-blackbuster'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-blackbuster'), (select id from public.allergens where code = 'milk'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-redmagic'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-redmagic'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-redmagic'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-redmagic'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-redmagic'), (select id from public.allergens where code = 'milk'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-redmagic'), (select id from public.allergens where code = 'tomato'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-gangjeong'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-gangjeong'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-gangjeong'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-gangjeong'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-gangjeong'), (select id from public.allergens where code = 'tomato'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-bone-gangjeong'), (select id from public.allergens where code = 'peanut'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-fried'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-fried'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-fried'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-fried'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yangnyeom'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yangnyeom'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yangnyeom'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yangnyeom'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yangnyeom'), (select id from public.allergens where code = 'tomato'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yangnyeom'), (select id from public.allergens where code = 'egg'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-hwasal'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-hwasal'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-hwasal'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-hwasal'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-hwasal'), (select id from public.allergens where code = 'shellfish'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(굴)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-blackbuster'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-blackbuster'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-blackbuster'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-blackbuster'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-blackbuster'), (select id from public.allergens where code = 'milk'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-redmagic'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-redmagic'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-redmagic'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-redmagic'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-redmagic'), (select id from public.allergens where code = 'milk'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-redmagic'), (select id from public.allergens where code = 'tomato'), 'contains', '닭고기, 대두, 밀, 쇠고기, 우유, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-gangjeong'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-gangjeong'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-gangjeong'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-gangjeong'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-gangjeong'), (select id from public.allergens where code = 'tomato'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-gangjeong'), (select id from public.allergens where code = 'peanut'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토, 땅콩', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chippurin'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 난류, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chippurin'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 난류, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chippurin'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 난류, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chippurin'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 난류, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chippurin'), (select id from public.allergens where code = 'egg'), 'contains', '닭고기, 대두, 밀, 쇠고기, 난류, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chippurin'), (select id from public.allergens where code = 'milk'), 'contains', '닭고기, 대두, 밀, 쇠고기, 난류, 우유', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-pandora'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-pandora'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-pandora'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-pandora'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-pandora'), (select id from public.allergens where code = 'tomato'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-oriental-pa'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-oriental-pa'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-oriental-pa'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-oriental-pa'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-oriental-pa'), (select id from public.allergens where code = 'egg'), 'contains', '닭고기, 대두, 밀, 쇠고기, 계란', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-cream-onion'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 알류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-cream-onion'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 알류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-cream-onion'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 알류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-cream-onion'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 알류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-cream-onion'), (select id from public.allergens where code = 'egg'), 'contains', '닭고기, 대두, 밀, 쇠고기, 알류', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-tangsuyuk'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-tangsuyuk'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-tangsuyuk'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-tangsuyuk'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-tangsuyuk'), (select id from public.allergens where code = 'shellfish'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yuringi'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yuringi'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yuringi'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yuringi'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-yuringi'), (select id from public.allergens where code = 'shellfish'), 'contains', '닭고기, 대두, 밀, 쇠고기, 조개류(가리비)', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chili'), (select id from public.allergens where code = 'chicken'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chili'), (select id from public.allergens where code = 'soybean'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chili'), (select id from public.allergens where code = 'wheat'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chili'), (select id from public.allergens where code = 'beef'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1)),
  ((select id from public.menus where slug = 'dasarang-boneless-chili'), (select id from public.allergens where code = 'tomato'), 'contains', '닭고기, 대두, 밀, 쇠고기, 토마토', (select id from public.data_sources where brand_id = (select id from public.brands where slug = 'dasarang') and url = 'https://xn--2j1bs2g1tjbiouwc.com/menu03?sca=%EC%B9%98%ED%82%A8#point' limit 1))
;

commit;
